name: Build
on:
  pull_request:
  push:
    branches:
      - main
      - develop
      - hotfix/*
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Get the sources
        uses: actions/checkout@v2

      - name: Run Cake script
        run: |
          dotnet tool restore
          dotnet cake